### ISSUE TITLE
如何导入目标IP的TXT？ ladon.exe target.txt OsScan 例如这样

### ISSUE THREAD

**Issue by cwh945** [k8gege/Ladon#1]
如何导入目标IP的TXT？ ladon.exe target.txt OsScan 例如这样

**Comment by k8gege** [comment]
> 
> 
> 如何导入目标IP的TXT？ ladon.exe target.txt OsScan 例如这样

程序目录下放ip.txt，然后运行ladon OsScan
同理ip24.txt/ip16.txt/url.txt/host.txt/domain.txt等也是一样

**Comment by cwh945** [comment]
谢谢大佬！
