### ISSUE TITLE
SmbScan 报错

### ISSUE THREAD

**Issue by phantom0000** [k8gege/Ladon#11]
环境: Windows 2008 R2 x64
Ladon40 可以使用，Ladon .net 2.x 调用SmbScan扫描时报错

![image](https://user-images.githubusercontent.com/12782343/71483211-b7cef380-2841-11ea-816b-8d52fc0f6669.png)
System.IO.FileNotFoundException: 未能加载文件或程序集“System.Core, Version=3.5.
0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”或它的某一个依赖项。系统
找不到指定的文件。
文件名:“System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561
934e089”
   在 SharpCifs.Util.Sharpen.Extensions.Contains[T](ICollection`1 col, Object it
em)
   在 SharpCifs.Util.Sharpen.Runtime.GetProperty(String key)
   在 SharpCifs.Config..cctor()

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!Enabl
eLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by k8gege** [comment]
> 环境: Windows 2008 R2 x64
> Ladon40 可以使用，Ladon .net 2.x 调用SmbScan扫描时报错

> System.IO.FileNotFoundException: 未能加载文件或程序集“System.Core, Version=3.5.
> 0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”或它的某一个依赖项。系统
> 找不到指定的文件。
> 文件名:“System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561

Bug原因:
这是由于2008默认未启用.Net 3.5运行时,而SharpCifs.dll中77个函数为.net 3.5所有
虽说.net 2.0与.net 3.5都是运行时都是2.0，但遇到2.0中没有的函数时自然会报错
其它模块没有出现同样的问题，是因为我优先采用最低版本开发 ,让其向后兼容。

解决方案:
命令行下启用.net 3.5运行时即可(GUI也可在服务器管理添加角色里启用)
 ![image](https://k8gege.org/k8img/Ladon/Win2008_SmbScan.png)
