### ISSUE TITLE
请问，解压密码是啥？

### ISSUE THREAD

**Issue by 0nlyuAarOn** [k8gege/Ladon#12]
大佬，解压密码是多少？。。。

**Comment by 376tian** [comment]
k8gege

**Comment by k8gege** [comment]
> 大佬，解压密码是多少？。。。

k8gege
k8gege.org

**Comment by xxsmile123** [comment]
k8gege.org是可以用的

**Comment by Axiso** [comment]
解压之后exe文件自动消失了，只剩下txt文件。是不是发生了什么不好的事情

**Comment by AdminHcat** [comment]
> 解压之后exe文件自动消失了，只剩下txt文件。是不是发生了什么不好的事情

检查安全软件
