### ISSUE TITLE
noping功能有点迷

### ISSUE THREAD

**Issue by xirotech** [k8gege/Ladon#19]
ladon40.exe noping 172.16.1.134 smbscan   会把整个ip段都扫一遍 就有点迷了
就因为加了个 noping 选项 ,不加就是正常的只扫一个单独ip

**Comment by k8gege** [comment]
> ladon40.exe noping 172.16.1.134 smbscan 会把整个ip段都扫一遍 就有点迷了
> 就因为加了个 noping 选项 ,不加就是正常的只扫一个单独ip

感谢反馈已修复（更新的时候，误注释了一行代码）
