### ISSUE TITLE
建议新增一个telnet爆破模块

### ISSUE THREAD

**Issue by Old-stan** [k8gege/Ladon#22]
还有Ladon下的依赖dll其实是在K8CScan库上，建议移到这个库里

**Comment by k8gege** [comment]
> 
> 
> 还有Ladon下的依赖dll其实是在K8CScan库上，建议移到这个库里

7.0后的EXE版都不再依赖DLL，需要依赖的是旧版或CS版，因为CS大小限制所以很多DLL无法打包。
