### ISSUE TITLE
源码如何编译，缺少一些包

### ISSUE THREAD

**Issue by st0rmspirit** [k8gege/Ladon#38]
![image](https://user-images.githubusercontent.com/13938323/97694505-a0097100-1add-11eb-87dd-8fc01a7e9f25.png)

搜到的包却无法安装成功
![image](https://user-images.githubusercontent.com/13938323/97694342-591b7b80-1add-11eb-8a02-87ceac4ffe37.png)

**Comment by TryA9ain** [comment]
1、用win2008 打开，找到这个文件，添加个引用
`C:\Windows\assembly\GAC_MSIL\System.Management.Automation\1.0.0.0__31bf3856ad364e35\System.Management.Automation.dll`
2、再添加个System.Management 引用即可
![image](https://user-images.githubusercontent.com/51145610/133754395-98548eed-dfdb-454e-8d2f-7f6a0ec914db.png)
