### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Bald-mans** [k8gege/Ladon#39]
ladon和ladon40两个exe程序打开后都会闪退，其他均正常

**Comment by k8gege** [comment]
> 
> 
> ladon和ladon40两个exe程序打开后都会闪退，其他均正常

WIKI：http://k8gege.org/Ladon

**Comment by sinlee1** [comment]
- 环境：Windows2008R2 环境下测试，出现以下错误，图形化和命令行的错误是一样的

![image](https://user-images.githubusercontent.com/29684167/102972033-667d4100-4535-11eb-8410-3ca483afe0c4.png)
