### ISSUE TITLE
CentOS7无法运行C#当前最新版Ladon  (应该是无解了)

### ISSUE THREAD

**Issue by Z-fly** [k8gege/Ladon#43]
![image](https://user-images.githubusercontent.com/10470892/103519852-34fb6280-4eb1-11eb-87a5-90abca4c1071.png)
![image](https://user-images.githubusercontent.com/10470892/103519868-39c01680-4eb1-11eb-9315-8369c2b4a87b.png)
https://www.codeweavers.com/support/wiki/diag/missinglibnss_mdns

**Comment by k8gege** [comment]
LadonGo全平台
https://github.com/k8gege/LadonGo
