### ISSUE TITLE
插件netscan的源代码在哪可以看到啊

### ISSUE THREAD

**Issue by sinmygit** [k8gege/Ladon#44]

**Comment by k8gege** [comment]
MoudleDemo.rar

**Comment by k8gege** [comment]
编写Ladon插件-批量检测网站是否使用Shiro
http://k8gege.org/Ladon/IsShiro.html

**Comment by k8gege** [comment]
Ladon插件实例内网Web扫描C#源码 
http://k8gege.org/p/da863d02.html
