### ISSUE TITLE
真正执行的地方都是二进制数据，安全人员敢用吗？

### ISSUE THREAD

**Issue by boy-trump** [k8gege/Ladon#6]
Program.cs 中扫描的的地方都是二进制的，安全人员生产环境敢用吗？
用了后企业内网全打趴下咋办？

**Comment by k8gege** [comment]
> Program.cs 中扫描的的地方都是二进制的，安全人员生产环境敢用吗？
> 用了后企业内网全打趴下咋办？

我也很想知道哪个模块可以把内网全打趴下
