### ISSUE TITLE
cs 4.5 插件乱码

### ISSUE THREAD

**Issue by cqrlhz** [k8gege/Ladon#64]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/63200706/179502628-10bc4e31-21ff-4709-8c5f-37db843379c4.png">

**Comment by k8gege** [comment]
K8哥哥's BLOG
    http://qqhack8.blog.163.com

**Comment by k8gege** [comment]
> <img alt="image" width="464" src="https://user-images.githubusercontent.com/63200706/179502628-10bc4e31-21ff-4709-8c5f-37db843379c4.png">

http://k8gege.org/Ladon/cs911.html
