### ISSUE TITLE
解压密码是多少啊？

### ISSUE THREAD

**Issue by acvxd** [k8gege/Ladon#67]

**Comment by k8gege** [comment]
K8哥哥's BLOG
    http://k8gege.org

**Comment by skybeast235** [comment]
Brother I didnt find the password on http://k8gege.org can you mention it.
Else we have to download from your blog website?

**Comment by k8gege** [comment]
K8哥哥's BLOG
    http://k8gege.org

**Comment by lppyyy** [comment]
the passwo is “k8gege.org”

> Brother I didnt find the password on http://k8gege.org can you mention it. Else we have to download from your blog website?
